services:
  resfin.webapi:
    image: ${DOCKER_REGISTRY-}resfinwebapi
    container_name: ResFin.WebApi
    build:
      context: .
      dockerfile: ResFin.WebApi/Dockerfile
    depends_on:
      - resfin-db
  
  resfin-db:
    image: postgres:latest
    container_name: ResFin.Db
    environment:
      - POSTGRES_DB=resfin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  # resfin-app:
  #   build: .
  #   depends_on:
  #     - resfin-db
  #   environment:
  #     ConnectionStrings__DefaultConnection: "Host=resfin-db;Port=5432;Database=resfin;Username=postgres;Password=postgress"

  resfin-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: ResFin.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm.json
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/resfin-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080

  resfin-seq:
    image: datalust/seq:latest
    container_name: Resfin.Seq
    environment:
       - ACCEPT_EULA=Y
    ports:
       - '5341:5341'
       - 8081:80

 
  resfin-redis:
    image: redis:latest
    container_name: Resfin.Redis
    restart: always
    ports:
       - '6379:6379'

